spring.application.name=backend

# Conexión a PostgreSQL en Azure
spring.datasource.url=jdbc:postgresql://db-helpdesk-goyco31.postgres.database.azure.com:5432/postgres
spring.datasource.username=goyco31
spring.datasource.password=PON_AQUI_TU_CONTRASEÑA

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true